<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="5" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-10-15T04:36:43Z" name="Suite" finished-at="2019-10-15T04:36:43Z" duration-ms="72">
    <groups>
      <group name="G1">
        <method signature="dependsOnMethodTest.f3()[pri:0, instance:dependsOnMethodTest@3c3d9b6b]" name="f3" class="dependsOnMethodTest"/>
        <method signature="dependsOnMethodTest.f4()[pri:0, instance:dependsOnMethodTest@3c3d9b6b]" name="f4" class="dependsOnMethodTest"/>
        <method signature="dependsOnMethodTest.f5()[pri:0, instance:dependsOnMethodTest@3c3d9b6b]" name="f5" class="dependsOnMethodTest"/>
      </group> <!-- G1 -->
    </groups>
    <test started-at="2019-10-15T04:36:43Z" name="Test" finished-at="2019-10-15T04:36:43Z" duration-ms="72">
      <class name="dependsOnMethodTest">
        <test-method signature="f3()[pri:0, instance:dependsOnMethodTest@3c3d9b6b]" started-at="2019-10-15T04:36:43Z" name="f3" finished-at="2019-10-15T04:36:43Z" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at dependsOnMethodTest.f3(dependsOnMethodTest.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f3 -->
        <test-method signature="f4()[pri:0, instance:dependsOnMethodTest@3c3d9b6b]" started-at="2019-10-15T04:36:43Z" name="f4" finished-at="2019-10-15T04:36:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f4 -->
        <test-method signature="f5()[pri:0, instance:dependsOnMethodTest@3c3d9b6b]" started-at="2019-10-15T04:36:43Z" name="f5" finished-at="2019-10-15T04:36:43Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f5 -->
      </class> <!-- dependsOnMethodTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
